# This file was produced by generate.py.  Do not edit it by hand.

from __future__ import annotations

from abc import abstractmethod

from types import EllipsisType

from typing import Self, Generic, overload, Literal, TypeVar, TypeVarTuple

from encodable import Encodable

A0 = TypeVar('A0')
A1 = TypeVar('A1')
A2 = TypeVar('A2')
A3 = TypeVar('A3')
A4 = TypeVar('A4')
Shape = TypeVarTuple('Shape')
Rest = TypeVarTuple('Rest')

Scalar = float

fallback_encoding: type | None = None


def encoding(cls, *clss): ...

class Pixels(Encodable, Generic[*Shape]):

    @property
    @abstractmethod
    def shape(self) -> tuple[*Shape]: ...

    @property
    @abstractmethod
    def precision(self) -> int: ...

    @property
    def denominator(self) -> int: ...

    @property
    def rank(self) -> int: ...

    def __len__(self: Pixels[A1, *tuple]) -> A1: ...

    def __repr__(self) -> str: ...

    @classmethod
    def zeros(cls, shape: tuple[*Rest]) -> Pixels[*Rest]: ...

    @classmethod
    def _zeros_(cls, shape: tuple[*Rest]) -> Pixels[*Rest]: ...

    @classmethod
    def ones(cls, shape: tuple[*Rest]) -> Pixels[*Rest]: ...

    @classmethod
    def _ones_(cls, shape: tuple[*Rest]) -> Pixels[*Rest]: ...

    # getitem

    @overload
    def __getitem__(self: Pixels[*Rest], index: tuple[()]) -> Pixels[*Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, *Rest], index: tuple[int]) -> Pixels[*Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, *Rest], index: tuple[slice]) -> Pixels[A0, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, *Rest], index: tuple[int, int]) -> Pixels[*Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, *Rest], index: tuple[int, slice]) -> Pixels[A1, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, *Rest], index: tuple[slice, int]) -> Pixels[A0, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, *Rest], index: tuple[slice, slice]) -> Pixels[A0, A1, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[int, int, int]) -> Pixels[*Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[int, int, slice]) -> Pixels[A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[int, slice, int]) -> Pixels[A1, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[int, slice, slice]) -> Pixels[A1, A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[slice, int, int]) -> Pixels[A0, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[slice, int, slice]) -> Pixels[A0, A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[slice, slice, int]) -> Pixels[A0, A1, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, *Rest], index: tuple[slice, slice, slice]) -> Pixels[A0, A1, A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, int, int, int]) -> Pixels[*Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, int, int, slice]) -> Pixels[A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, int, slice, int]) -> Pixels[A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, int, slice, slice]) -> Pixels[A2, A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, slice, int, int]) -> Pixels[A1, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, slice, int, slice]) -> Pixels[A1, A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, slice, slice, int]) -> Pixels[A1, A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[int, slice, slice, slice]) -> Pixels[A1, A2, A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, int, int, int]) -> Pixels[A0, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, int, int, slice]) -> Pixels[A0, A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, int, slice, int]) -> Pixels[A0, A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, int, slice, slice]) -> Pixels[A0, A2, A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, slice, int, int]) -> Pixels[A0, A1, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, slice, int, slice]) -> Pixels[A0, A1, A3, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, slice, slice, int]) -> Pixels[A0, A1, A2, *Rest]: ...

    @overload
    def __getitem__(self: Pixels[A0, A1, A2, A3, *Rest], index: tuple[slice, slice, slice, slice]) -> Pixels[A0, A1, A2, A3, *Rest]: ...

    def __getitem__(self: Pixels, index: EllipsisType | int | slice | tuple[int | slice, ...]) -> Pixels: ...

    def _getitem_(self, index: tuple[int | slice, ...]) -> Pixels[*tuple[int, ...]]: ...

    # permute

    @overload
    def permute(self: Pixels[()], /) -> Pixels[()]: ...

    @overload
    def permute(self: Pixels[A0], i0: int, /) -> Pixels[A0]: ...

    @overload
    def permute(self: Pixels[A0, A1], i0: Literal[0], i1: int, /) -> Pixels[A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1], i0: int, i1: Literal[0], /) -> Pixels[A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1], i0: Literal[1], i1: int, /) -> Pixels[A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1], i0: int, i1: Literal[1], /) -> Pixels[A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1], i0: int, i1: int, /) -> Pixels[A0 | A1, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[2], i1: int, i2: Literal[1], /) -> Pixels[A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[0], i1: int, i2: Literal[2], /) -> Pixels[A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[0], i2: Literal[2], /) -> Pixels[A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[2], i1: Literal[0], i2: int, /) -> Pixels[A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[2], i1: int, i2: Literal[0], /) -> Pixels[A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[2], i2: Literal[1], /) -> Pixels[A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[0], i1: Literal[1], i2: int, /) -> Pixels[A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[0], i1: int, i2: Literal[1], /) -> Pixels[A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[0], i1: Literal[2], i2: int, /) -> Pixels[A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[1], i1: Literal[0], i2: int, /) -> Pixels[A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[1], i1: int, i2: Literal[0], /) -> Pixels[A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[1], i1: Literal[2], i2: int, /) -> Pixels[A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[0], i2: Literal[1], /) -> Pixels[A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[2], i1: Literal[1], i2: int, /) -> Pixels[A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[1], i1: int, i2: Literal[2], /) -> Pixels[A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[1], i2: Literal[0], /) -> Pixels[A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[1], i2: Literal[2], /) -> Pixels[A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[2], i2: Literal[0], /) -> Pixels[A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[0], i2: int, /) -> Pixels[A1 | A2, A0, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: int, i2: Literal[0], /) -> Pixels[A1 | A2, A1 | A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: int, i2: Literal[2], /) -> Pixels[A0 | A1, A0 | A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[2], i1: int, i2: int, /) -> Pixels[A2, A0 | A1, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[1], i2: int, /) -> Pixels[A0 | A2, A1, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[1], i1: int, i2: int, /) -> Pixels[A1, A0 | A2, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: int, i2: Literal[1], /) -> Pixels[A0 | A2, A0 | A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: Literal[2], i2: int, /) -> Pixels[A0 | A1, A2, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: Literal[0], i1: int, i2: int, /) -> Pixels[A0, A1 | A2, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2], i0: int, i1: int, i2: int, /) -> Pixels[A0 | A1 | A2, A0 | A1 | A2, A0 | A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[0], i3: Literal[3], /) -> Pixels[A2, A1, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[3], i2: int, i3: Literal[2], /) -> Pixels[A0, A3, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[0], i3: Literal[2], /) -> Pixels[A3, A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[2], i3: Literal[0], /) -> Pixels[A3, A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[0], i3: Literal[1], /) -> Pixels[A3, A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[2], i2: Literal[3], i3: int, /) -> Pixels[A1, A2, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[1], i2: Literal[2], i3: int, /) -> Pixels[A3, A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[2], i2: Literal[0], i3: int, /) -> Pixels[A3, A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[1], i3: Literal[2], /) -> Pixels[A0, A3, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[1], i3: Literal[0], /) -> Pixels[A3, A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[2], i3: Literal[3], /) -> Pixels[A0, A1, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[2], i2: int, i3: Literal[0], /) -> Pixels[A3, A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[2], i3: Literal[1], /) -> Pixels[A3, A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[1], i2: int, i3: Literal[0], /) -> Pixels[A3, A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[0], i3: Literal[3], /) -> Pixels[A1, A2, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[0], i2: Literal[3], i3: int, /) -> Pixels[A1, A0, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[0], i2: int, i3: Literal[2], /) -> Pixels[A1, A0, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[1], i3: Literal[2], /) -> Pixels[A3, A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[1], i2: int, i3: Literal[3], /) -> Pixels[A0, A1, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[3], i2: Literal[0], i3: int, /) -> Pixels[A1, A3, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[2], i2: int, i3: Literal[1], /) -> Pixels[A0, A2, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[2], i2: Literal[1], i3: int, /) -> Pixels[A3, A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[1], i2: int, i3: Literal[2], /) -> Pixels[A3, A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[3], i2: Literal[2], i3: int, /) -> Pixels[A1, A3, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[0], i3: Literal[1], /) -> Pixels[A2, A3, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[0], i3: Literal[2], /) -> Pixels[A1, A3, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[3], i2: Literal[1], i3: int, /) -> Pixels[A0, A3, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[2], i2: int, i3: Literal[3], /) -> Pixels[A0, A2, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[0], i2: int, i3: Literal[3], /) -> Pixels[A2, A0, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[1], i2: Literal[0], i3: int, /) -> Pixels[A3, A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[0], i3: Literal[1], /) -> Pixels[A2, A3, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[3], i3: Literal[0], /) -> Pixels[A1, A2, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[1], i2: Literal[2], i3: int, /) -> Pixels[A0, A1, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[0], i3: Literal[2], /) -> Pixels[A3, A1, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[1], i2: Literal[3], i3: int, /) -> Pixels[A2, A1, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[0], i3: Literal[3], /) -> Pixels[A2, A1, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[3], i3: Literal[1], /) -> Pixels[A0, A2, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[2], i3: Literal[3], /) -> Pixels[A1, A0, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[3], i3: Literal[2], /) -> Pixels[A1, A0, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[3], i3: Literal[0], /) -> Pixels[A2, A1, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[3], i3: Literal[1], /) -> Pixels[A0, A2, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[0], i2: int, i3: Literal[2], /) -> Pixels[A3, A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[3], i3: Literal[2], /) -> Pixels[A0, A1, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[3], i2: Literal[1], i3: int, /) -> Pixels[A2, A3, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[0], i2: Literal[1], i3: int, /) -> Pixels[A3, A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[1], i3: Literal[3], /) -> Pixels[A0, A2, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[2], i3: Literal[1], /) -> Pixels[A3, A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[2], i3: Literal[0], /) -> Pixels[A1, A3, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[1], i3: Literal[2], /) -> Pixels[A3, A0, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[3], i2: int, i3: Literal[1], /) -> Pixels[A2, A3, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[3], i2: int, i3: Literal[1], /) -> Pixels[A0, A3, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[0], i3: Literal[1], /) -> Pixels[A3, A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[2], i3: Literal[3], /) -> Pixels[A1, A0, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[3], i3: Literal[2], /) -> Pixels[A1, A0, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[2], i2: Literal[0], i3: int, /) -> Pixels[A1, A2, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[0], i3: Literal[3], /) -> Pixels[A1, A2, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[2], i3: Literal[0], /) -> Pixels[A1, A3, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[3], i3: Literal[1], /) -> Pixels[A2, A0, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[2], i3: Literal[0], /) -> Pixels[A3, A1, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[1], i3: Literal[3], /) -> Pixels[A2, A0, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[2], i3: Literal[1], /) -> Pixels[A0, A3, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[1], i3: Literal[3], /) -> Pixels[A0, A2, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[2], i2: int, i3: Literal[3], /) -> Pixels[A1, A2, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[1], i2: int, i3: Literal[2], /) -> Pixels[A0, A1, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[1], i2: Literal[3], i3: int, /) -> Pixels[A0, A1, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[3], i2: int, i3: Literal[0], /) -> Pixels[A1, A3, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[1], i2: int, i3: Literal[3], /) -> Pixels[A2, A1, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[2], i2: int, i3: Literal[1], /) -> Pixels[A3, A2, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[1], i3: Literal[0], /) -> Pixels[A3, A2, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[0], i2: Literal[2], i3: int, /) -> Pixels[A1, A0, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[2], i3: Literal[3], /) -> Pixels[A0, A1, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[2], i2: Literal[1], i3: int, /) -> Pixels[A0, A2, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[0], i2: Literal[1], i3: int, /) -> Pixels[A2, A0, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[0], i2: int, i3: Literal[3], /) -> Pixels[A1, A0, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[3], i3: Literal[2], /) -> Pixels[A0, A1, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[3], i3: Literal[0], /) -> Pixels[A1, A2, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[3], i2: int, i3: Literal[2], /) -> Pixels[A1, A3, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[0], i2: int, i3: Literal[1], /) -> Pixels[A3, A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[2], i2: Literal[3], i3: int, /) -> Pixels[A0, A2, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[0], i2: Literal[3], i3: int, /) -> Pixels[A2, A0, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[3], i2: Literal[2], i3: int, /) -> Pixels[A0, A3, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[0], i3: Literal[2], /) -> Pixels[A1, A3, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[0], i2: Literal[2], i3: int, /) -> Pixels[A3, A0, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[3], i2: Literal[0], i3: int, /) -> Pixels[A2, A3, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[0], i2: int, i3: Literal[1], /) -> Pixels[A2, A0, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[1], i3: Literal[0], /) -> Pixels[A2, A3, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[3], i2: int, i3: Literal[0], /) -> Pixels[A2, A3, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[3], i3: Literal[1], /) -> Pixels[A2, A0, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[1], i3: Literal[0], /) -> Pixels[A2, A3, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[2], i3: Literal[1], /) -> Pixels[A0, A3, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[2], i2: int, i3: Literal[0], /) -> Pixels[A1, A2, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[1], i2: Literal[0], i3: int, /) -> Pixels[A2, A1, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[1], i3: Literal[3], /) -> Pixels[A2, A0, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[1], i2: int, i3: Literal[0], /) -> Pixels[A2, A1, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[3], i3: Literal[0], /) -> Pixels[A2, A1, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[1], i3: Literal[2], /) -> Pixels[A0, A3, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[1], i2: int, i3: int, /) -> Pixels[A3, A1, A0 | A2, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[3], i3: Literal[1], /) -> Pixels[A0 | A2, A0 | A2, A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: int, i3: Literal[3], /) -> Pixels[A0, A1 | A2, A1 | A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: int, i3: Literal[1], /) -> Pixels[A0 | A3, A2, A0 | A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[1], i3: Literal[3], /) -> Pixels[A0 | A2, A0 | A2, A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: int, i3: Literal[2], /) -> Pixels[A0 | A3, A1, A0 | A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[0], i2: int, i3: int, /) -> Pixels[A3, A0, A1 | A2, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: int, i3: Literal[3], /) -> Pixels[A0 | A1, A2, A0 | A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[1], i3: int, /) -> Pixels[A2 | A3, A0, A1, A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[0], i3: int, /) -> Pixels[A2 | A3, A1, A0, A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[3], i3: int, /) -> Pixels[A1 | A2, A0, A3, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[2], i3: Literal[0], /) -> Pixels[A1 | A3, A1 | A3, A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[2], i3: int, /) -> Pixels[A0 | A1, A3, A2, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[2], i3: int, /) -> Pixels[A0, A1 | A3, A2, A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[0], i3: Literal[2], /) -> Pixels[A1 | A3, A1 | A3, A0, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: int, i3: Literal[1], /) -> Pixels[A2, A0 | A3, A0 | A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[0], i3: int, /) -> Pixels[A1 | A3, A2, A0, A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: int, i3: Literal[1], /) -> Pixels[A3, A0 | A2, A0 | A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[1], i2: int, i3: int, /) -> Pixels[A0, A1, A2 | A3, A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: int, i3: Literal[3], /) -> Pixels[A2, A0 | A1, A0 | A1, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[3], i3: int, /) -> Pixels[A0 | A2, A1, A3, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: int, i3: Literal[2], /) -> Pixels[A0, A1 | A3, A1 | A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: int, i3: Literal[0], /) -> Pixels[A1 | A3, A2, A1 | A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[2], i2: int, i3: int, /) -> Pixels[A0, A2, A1 | A3, A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: int, i3: Literal[2], /) -> Pixels[A1 | A3, A0, A1 | A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[3], i2: int, i3: int, /) -> Pixels[A1, A3, A0 | A2, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[0], i2: int, i3: int, /) -> Pixels[A2, A0, A1 | A3, A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[0], i3: int, /) -> Pixels[A2, A1 | A3, A0, A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: int, i3: Literal[0], /) -> Pixels[A1 | A2, A3, A1 | A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[2], i3: int, /) -> Pixels[A1, A0 | A3, A2, A0 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[0], i3: Literal[1], /) -> Pixels[A2 | A3, A2 | A3, A0, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: int, i3: Literal[0], /) -> Pixels[A2, A1 | A3, A1 | A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[1], i3: Literal[0], /) -> Pixels[A2 | A3, A2 | A3, A1, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[1], i3: int, /) -> Pixels[A0 | A2, A3, A1, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: int, i3: Literal[3], /) -> Pixels[A1, A0 | A2, A0 | A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[2], i3: Literal[1], /) -> Pixels[A0 | A3, A0 | A3, A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[2], i3: int, /) -> Pixels[A3, A0 | A1, A2, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[3], i3: Literal[0], /) -> Pixels[A1 | A2, A1 | A2, A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: int, i3: Literal[2], /) -> Pixels[A0 | A1, A3, A0 | A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[3], i3: int, /) -> Pixels[A0, A1 | A2, A3, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[1], i3: Literal[2], /) -> Pixels[A0 | A3, A0 | A3, A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[0], i3: Literal[3], /) -> Pixels[A1 | A2, A1 | A2, A0, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[1], i3: int, /) -> Pixels[A0 | A3, A2, A1, A0 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[2], i3: Literal[3], /) -> Pixels[A0 | A1, A0 | A1, A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[3], i3: Literal[2], /) -> Pixels[A0 | A1, A0 | A1, A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: Literal[0], i3: int, /) -> Pixels[A1 | A2, A3, A0, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: Literal[3], i3: int, /) -> Pixels[A0 | A1, A2, A3, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: int, i3: Literal[1], /) -> Pixels[A2 | A3, A0, A2 | A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: int, i3: Literal[3], /) -> Pixels[A0 | A2, A1, A0 | A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: Literal[2], i3: int, /) -> Pixels[A1 | A3, A0, A2, A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[0], i3: int, /) -> Pixels[A1, A2 | A3, A0, A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: int, i3: Literal[3], /) -> Pixels[A1 | A2, A0, A1 | A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: int, i3: Literal[0], /) -> Pixels[A1, A2 | A3, A2 | A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: Literal[3], i2: int, i3: int, /) -> Pixels[A0, A3, A1 | A2, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[3], i2: int, i3: int, /) -> Pixels[A2, A3, A0 | A1, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[0], i3: int, /) -> Pixels[A3, A1 | A2, A0, A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[1], i3: int, /) -> Pixels[A2, A0 | A3, A1, A0 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: Literal[1], i3: int, /) -> Pixels[A0, A2 | A3, A1, A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[2], i2: int, i3: int, /) -> Pixels[A1, A2, A0 | A3, A0 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: int, i3: Literal[0], /) -> Pixels[A3, A1 | A2, A1 | A2, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: Literal[1], i2: int, i3: int, /) -> Pixels[A2, A1, A0 | A3, A0 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: Literal[3], i3: int, /) -> Pixels[A2, A0 | A1, A3, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: int, i3: Literal[2], /) -> Pixels[A1, A0 | A3, A0 | A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: Literal[2], i3: int, /) -> Pixels[A0 | A3, A1, A2, A0 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: int, i3: Literal[1], /) -> Pixels[A0 | A2, A3, A0 | A2, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: int, i3: Literal[1], /) -> Pixels[A0, A2 | A3, A2 | A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: Literal[0], i2: int, i3: int, /) -> Pixels[A1, A0, A2 | A3, A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: int, i3: Literal[2], /) -> Pixels[A3, A0 | A1, A0 | A1, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: Literal[3], i3: int, /) -> Pixels[A1, A0 | A2, A3, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: Literal[1], i3: int, /) -> Pixels[A3, A0 | A2, A1, A0 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: int, i3: Literal[0], /) -> Pixels[A2 | A3, A1, A2 | A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: Literal[2], i2: int, i3: int, /) -> Pixels[A3, A2, A0 | A1, A0 | A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: int, i3: Literal[0], /) -> Pixels[A1 | A2 | A3, A1 | A2 | A3, A1 | A2 | A3, A0]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[0], i1: int, i2: int, i3: int, /) -> Pixels[A0, A1 | A2 | A3, A1 | A2 | A3, A1 | A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[1], i3: int, /) -> Pixels[A0 | A2 | A3, A0 | A2 | A3, A1, A0 | A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: int, i3: Literal[2], /) -> Pixels[A0 | A1 | A3, A0 | A1 | A3, A0 | A1 | A3, A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[2], i2: int, i3: int, /) -> Pixels[A0 | A1 | A3, A2, A0 | A1 | A3, A0 | A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[3], i2: int, i3: int, /) -> Pixels[A0 | A1 | A2, A3, A0 | A1 | A2, A0 | A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[2], i1: int, i2: int, i3: int, /) -> Pixels[A2, A0 | A1 | A3, A0 | A1 | A3, A0 | A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[3], i3: int, /) -> Pixels[A0 | A1 | A2, A0 | A1 | A2, A3, A0 | A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: int, i3: Literal[1], /) -> Pixels[A0 | A2 | A3, A0 | A2 | A3, A0 | A2 | A3, A1]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[1], i1: int, i2: int, i3: int, /) -> Pixels[A1, A0 | A2 | A3, A0 | A2 | A3, A0 | A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[0], i3: int, /) -> Pixels[A1 | A2 | A3, A1 | A2 | A3, A0, A1 | A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: Literal[3], i1: int, i2: int, i3: int, /) -> Pixels[A3, A0 | A1 | A2, A0 | A1 | A2, A0 | A1 | A2]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: Literal[2], i3: int, /) -> Pixels[A0 | A1 | A3, A0 | A1 | A3, A2, A0 | A1 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[1], i2: int, i3: int, /) -> Pixels[A0 | A2 | A3, A1, A0 | A2 | A3, A0 | A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: int, i3: Literal[3], /) -> Pixels[A0 | A1 | A2, A0 | A1 | A2, A0 | A1 | A2, A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: Literal[0], i2: int, i3: int, /) -> Pixels[A1 | A2 | A3, A0, A1 | A2 | A3, A1 | A2 | A3]: ...

    @overload
    def permute(self: Pixels[A0, A1, A2, A3], i0: int, i1: int, i2: int, i3: int, /) -> Pixels[A0 | A1 | A2 | A3, A0 | A1 | A2 | A3, A0 | A1 | A2 | A3, A0 | A1 | A2 | A3]: ...

    def permute(self, *permutation: int) -> Pixels: ...

    def _permute_(self, permutation: tuple[int, ...]) -> Pixels: ...

    # bool

    def __bool__(self) -> bool: ...

    def _bool_(self) -> bool: ...

    # lshift

    def __lshift__(self: Pixels[*Shape], amount: int) -> Pixels[*Shape]: ...

    def _lshift_(self: Self, amount: int) -> Self: ...

    # rshift

    def __rshift__(self: Pixels[*Shape], amount: int) -> Pixels[*Shape]: ...

    def _rshift_(self: Self, amount: int) -> Self: ...

    # pow

    def __pow__(self: Pixels[*Shape], exponent: float) -> Pixels[*Shape]: ...

    def _pow_(self: Self, exponent: float) -> Self: ...

    # abs

    def __abs__(self: Pixels[*Shape]) -> Pixels[*Shape]: ...

    def _abs_(self: Self) -> Self: ...

    # not

    def __not__(self: Pixels[*Shape]) -> Pixels[*Shape]: ...

    def _not_(self: Self) -> Self: ...

    # invert

    def __invert__(self: Pixels[*Shape]) -> Pixels[*Shape]: ...

    def _invert_(self: Self) -> Self: ...

    # neg

    def __neg__(self: Pixels[*Shape]) -> Pixels[*Shape]: ...

    def _neg_(self: Self) -> Self: ...

    # pos

    def __pos__(self: Pixels[*Shape]) -> Pixels[*Shape]: ...

    def _pos_(self: Self) -> Self: ...

    # broadcast_to

    def broadcast_to(self, shape: tuple[*Rest]) -> Pixels[*Rest]: ...

    def _broadcast_to_(self, shape: tuple[*Rest]) -> Pixels[*Rest]: ...

    # broadcast

    @overload
    def __broadcast__(self: Pixels[*Shape], other: Scalar) -> tuple[Pixels[*Shape], Pixels[*Shape]]: ...

    @overload
    def __broadcast__(self: Pixels[*Shape, A1, *Rest], other: Pixels[*Shape]) -> tuple[Pixels[*Shape, A1, *Rest], Pixels[*Shape, A1, *Rest]]: ...

    @overload
    def __broadcast__(self: Pixels[*Shape], other: Pixels[*Shape, A1, *Rest]) -> tuple[Pixels[*Shape, A1, *Rest], Pixels[*Shape, A1, *Rest]]: ...

    def __broadcast__(self: Pixels, other: Pixels | Scalar) -> tuple[Pixels, Pixels]: ...

    # add

    @overload
    def __add__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __add__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __add__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __add__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __radd__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _add_(self: Self, other: Self) -> Self: ...

    # and

    @overload
    def __and__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __and__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __and__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __and__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rand__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _and_(self: Self, other: Self) -> Self: ...

    # floordiv

    @overload
    def __floordiv__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __floordiv__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __floordiv__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __floordiv__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rfloordiv__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _floordiv_(self: Self, other: Self) -> Self: ...

    # mod

    @overload
    def __mod__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __mod__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __mod__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __mod__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rmod__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _mod_(self: Self, other: Self) -> Self: ...

    # mul

    @overload
    def __mul__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __mul__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __mul__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __mul__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rmul__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _mul_(self: Self, other: Self) -> Self: ...

    # or

    @overload
    def __or__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __or__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __or__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __or__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __ror__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _or_(self: Self, other: Self) -> Self: ...

    # sub

    @overload
    def __sub__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __sub__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __sub__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __sub__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rsub__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _sub_(self: Self, other: Self) -> Self: ...

    # truediv

    @overload
    def __truediv__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __truediv__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __truediv__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __truediv__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rtruediv__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _truediv_(self: Self, other: Self) -> Self: ...

    # xor

    @overload
    def __xor__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __xor__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __xor__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __xor__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def __rxor__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def _xor_(self: Self, other: Self) -> Self: ...

    # lt

    @overload
    def __lt__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __lt__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __lt__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __lt__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def _lt_(self: Self, other: Self) -> Self: ...

    # gt

    @overload
    def __gt__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __gt__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __gt__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __gt__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def _gt_(self: Self, other: Self) -> Self: ...

    # le

    @overload
    def __le__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __le__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __le__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __le__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def _le_(self: Self, other: Self) -> Self: ...

    # ge

    @overload
    def __ge__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __ge__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __ge__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __ge__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def _ge_(self: Self, other: Self) -> Self: ...

    # eq

    @overload
    def __eq__(self: Pixels[*Shape, A0, *Rest], other: Pixels[*Shape]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __eq__(self: Pixels[*Shape], other: Pixels[*Shape, A0, *Rest]) -> Pixels[*Shape, A0, *Rest]: ...

    @overload
    def __eq__(self: Pixels[*Shape], other: Scalar) -> Pixels[*Shape]: ...

    def __eq__(self: Pixels, other: Pixels | Scalar) -> Pixels: ...

    def _eq_(self: Self, other: Self) -> Self: ...

